### ISSUE TITLE
With Drupal 10.3+: the requested URL returned error: 500

### ISSUE THREAD

**Issue by andriokha** [ddev/ddev-selenium-standalone-chrome#41]
Hi,

I'm finding that the latest version of Drupal this works with is 10.2. It seems to be down to [#3240792](https://www.drupal.org/node/3240792) (see [comment #63](https://www.drupal.org/project/drupal/issues/3240792#comment-15481821) onwards).

The following passes when `$branch` is `10.2.x` but fails with `10.3.x`.

```sh
git clone --depth 1 https://git.drupalcode.org/project/drupal -b $branch
cd drupal
ddev delete -Oy test-drupal || true
ddev config --project-name=test-drupal --php-version=8.1 --web-environment-add SYMFONY_DEPRECATIONS_HELPER=disabled
ddev start -y
ddev composer -n require "drupal/core-dev:^10"
ddev get ddev/ddev-selenium-standalone-chrome
ddev restart
ddev exec "curl -v selenium-chrome:4444/wd/hub/status"
ddev exec -d /var/www/html "vendor/bin/phpunit -v -c ./core/phpunit.xml.dist ./core/modules/system/tests/src/FunctionalJavascript/FrameworkTest.php"
```

As a workaround I'm using https://raw.githubusercontent.com/ddev/ddev-contrib/master/docker-compose-services/drupalci-chromedriver/docker-compose.chromedriver.yaml which uses `drupalci/webdriver-chromedriver:production`.

Thanks!

**Comment by andriokha** [comment]
[phpunit.log](https://github.com/ddev/ddev-selenium-standalone-chrome/files/15038856/phpunit.log)
[selenium.log](https://github.com/ddev/ddev-selenium-standalone-chrome/files/15038853/selenium.log)

**Comment by andriokha** [comment]
It appears to be that `\WebDriver\WebDriver::session()` is checking for the `w3c` flag one level higher up than where it was being set, so it was using the W3C dialect, which won't be supported until [#3421202](https://www.drupal.org/project/drupal/issues/3421202) lands. Using the following worked for me: 
```
[\"chrome\", {\"browserName\":\"chrome\",\"w3c\":false,\"goog:chromeOptions\":{\"args\":[\"--disable-gpu\",\"--headless\", \"--no-sandbox\", \"--disable-dev-shm-usage\"]}}, \"http://selenium-chrome:4444/wd/hub\"]
```

**Comment by rfay** [comment]
Does that mean this gas nothing to do with this repo?

**Comment by andriokha** [comment]
I'm not sure I'm afraid. It seems to me either the config in this repo is wrong ([and would be fixed with this change](https://github.com/ddev/ddev-selenium-standalone-chrome/compare/main...FabbDev:ddev-selenium-standalone-chrome:fix-drupal-10-3)), or the new library being used ([lullabot/php-webdriver](https://github.com/Lullabot/php-webdriver)) is looking in the wrong place. I can't find any reference on the matter (this is a flag to switch between two different standards, so I guess it isn't in either standard itself). It's not mentioned as [a chrome capability here](https://chromedriver.chromium.org/capabilities) and it doesn't to my mind make much sense as a browser-specific capability. Quickly looking at some other webdrivers (ie I could easily have missed something) it seems that [Facebook's driver automatically detects dialect](https://github.com/php-webdriver/php-webdriver/blob/5d8e66ff849b5614015d35e99d759252e371ce26/CHANGELOG.md?plain=1#L136), so I guess no flag needed; and [instaclick's version seems to infer w3c mode from whether any capabilities are passed at all](https://github.com/instaclick/php-webdriver/blob/83b684018fcd60f37d22fd0b3e48e4a592eb874b/lib/WebDriver/Session.php#L126) (which makes no sense to me!).

So yeah, not much help overall! [I pinged this issue where](https://www.drupal.org/project/drupal/issues/3421202#comment-15561461) I expect bigger brains will weigh in (:

**Comment by thijsboots** [comment]
Thank you for posting that [fix](https://github.com/ddev/ddev-selenium-standalone-chrome/compare/main...FabbDev:ddev-selenium-standalone-chrome:fix-drupal-10-3?diff=unified&w=), @andriokha! Works perfectly on my machine.

**Comment by penyaskito** [comment]
Had the same issue, changing `.ddev/config.selenium-standalone-chrome.yaml` as suggested fixed it for me (working on contrib with 10.3.x HEAD)

**Comment by simesy** [comment]
This change also fixed for me. ddev v1.23.1, Drupal 10.3, `seleniarm/standalone-chromium:4.1.4-20220429`

**Comment by simesy** [comment]
I'm guessing this needs to be updated to a new image https://github.com/ddev/ddev-selenium-standalone-chrome/blob/main/docker-compose.selenium-chrome.yaml#L9

This core issure https://www.drupal.org/project/drupal/issues/3421202 is proposing 4.17 which is a couple of months old, versus this one is 2 years old.

**Comment by weitzman** [comment]
That upgrade has stalled. See #42

**Comment by slashrsm** [comment]
Changing `MINK_DRIVER_ARGS_WEBDRIVER` as proposed by @andriokha fixes this issue for me. Would it be possible to pull this fix upstream?

**Comment by andriokha** [comment]
See also https://github.com/Lullabot/php-webdriver/pull/10/files

**Comment by rfay** [comment]
@andriokha if you/@FabbDev have a PR to offer, would you please offer it here?

https://github.com/FabbDev/ddev-selenium-standalone-chrome/tree/fix-drupal-10-3 

I note that `bats tests` does not yet succeed on that branch.

**Comment by andriokha** [comment]
OK the PR for `lullabot/php-webdriver` got merged in. If some kind soul with perms could rerun the tests, with a bit of luck we'll  be able to close this issue I think.

**Comment by andriokha** [comment]
Nice, thanks @rfay!
