### ISSUE TITLE
Add Shortname Commands

### ISSUE THREAD

**Issue by alexfinnarn** [ddev/ddev-selenium-standalone-chrome#44]
I really like using this addon and even tried to create it myself before this project existed because I wanted to run functional JS tests on a Drupal project. 

I'm going through a codebase now that is using a custom `phpunit.xml` config file vs. the `phpunit.xml.dist` file Drupal core ships with. A colleague is reporting on another codebase that the config on that codebase can't autoload the classes under test. So, I told them to try out the commands listed in the readme.

And then I thought, can addons ship with commands already built in? I think the addons can copy files into certain directories but it's been a while since I looked at the ddev addon development process.

If possible, I propose adding commands to this repo that would have options for particular tests but abstract away what config files you need to load. Potentially a prefix `ssc` could be added to avoid any potential conflicts with existing commands on a ddev project. And that can give you examples like `ddev ssc-func-js` for functional JS runs and `ddev ssc-dtt` for using the DTT features...just initial thoughts.

Is this possible? If so, is it a good idea? I sure would like to use core's config and be able to type a nice command without having to create a custom one myself. I don't see any reason I would want to customize the config and definitely want to outsource that to addons like this + core devs vs. maintaining it myself.

**Comment by tyler36** [comment]
I find using phpunit's `--testsuit`, `--group` and `--filter` commands extremely useful.

You can target testsuites using `ddev . phpunit --testsuite FunctionJavascript`

I tend to make use of group annotations in my tests files

```php
/**
 * Test basic file functions.
 *
 * @group my_module
 * @group dtt
 */
```

Then I can use `ddev . phpunit --group dtt` to run all tests with `dtt` annotation.

**Comment by alexfinnarn** [comment]
I see this is not planned but thanks for the tips @tyler36 !
