### ISSUE TITLE
All tests are failing

### ISSUE THREAD

**Issue by rfay** [ddev/ddev-selenium-standalone-chrome#53]
All tests (both against HEAD and stable) are failing for the last few days. Could you take a look please? Thanks!

https://github.com/ddev/ddev-selenium-standalone-chrome/actions/runs/11792355249/job/32845871830

**Comment by tyler36** [comment]
The daily tests appear to be working again from "November 13, 2024 16:06" (the following 8 days also pass).

**Comment by tyler36** [comment]
Re-ran the last failing daily test (November 12, 2024 16:06) and it passes now.

**Comment by rfay** [comment]
Thanks!
